# Generated by Django 4.2.5 on 2023-09-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_userdetail_birthday_alter_userdetail_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_picture/'),
        ),
    ]
