# Generated by Django 4.2.5 on 2023-10-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
