# Generated by Django 4.2.5 on 2023-10-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_delete_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='image',
            field=models.ImageField(default='profile_picture/default.jpg', upload_to='profile_picture/'),
        ),
    ]
